const data = [
  {
    appId: 810,
    appName: "Asset Based Landing environmnet",
    state: "Operate",
    lob: "CB",
    JPMC_SOX: "Y",
    JPMC_CCAP: "Y",
    SSAE_SOCI: "Y",
    PCI: "N",
    PHI: "Y",
    GLBA: "N",
    MNPI: "Y",
    HVBE: "Y",
  },
  {
    appId: 1420,
    appName: "Sapphire",
    state: "Operate",
    lob: "CIB",
    JPMC_SOX: "Y",
    JPMC_CCAP: "Y",
    SSAE_SOCI: "N",
    PCI: "Y",
    PHI: "N",
    GLBA: "N",
    MNPI: "Y",
    HVBE: "N",
  },
  {
    appId: 1650,
    appName: "CME - BrokerTec",
    state: "Operate",
    lob: "CIB",
    JPMC_SOX: "N",
    JPMC_CCAP: "N",
    SSAE_SOCI: "N",
    PCI: "N",
    PHI: "Y",
    GLBA: "N",
    MNPI: "N",
    HVBE: "N",
  },
  {
    appId: 1800,
    appName: "RDT-Counterparty Account Setup System",
    state: "Operate",
    lob: "FRDC",
    JPMC_SOX: "N",
    JPMC_CCAP: "N",
    SSAE_SOCI: "Y",
    PCI: "N",
    PHI: "N",
    GLBA: "Y",
    MNPI: "N",
    HVBE: "N",
  },
  {
    appId: 1970,
    appName: "STFI Tools",
    state: "Operate",
    lob: "CIB",
    JPMC_SOX: "N",
    JPMC_CCAP: "N",
    SSAE_SOCI: "N",
    PCI: "Y",
    PHI: "N",
    GLBA: "N",
    MNPI: "N",
    HVBE: "N",
  },
  {
    appId: 2390,
    appName: "Nasdaq NFI GUI",
    state: "Operate",
    lob: "CIB",
    JPMC_SOX: "N",
    JPMC_CCAP: "N",
    SSAE_SOCI: "Y",
    PCI: "N",
    PHI: "N",
    GLBA: "N",
    MNPI: "N",
    HVBE: "N",
  },
  {
    appId: 4050,
    appName: "Customer and Bank Data",
    state: "Operate",
    lob: "CIB",
    JPMC_SOX: "N",
    JPMC_CCAP: "N",
    SSAE_SOCI: "N",
    PCI: "Y",
    PHI: "N",
    GLBA: "Y",
    MNPI: "N",
    HVBE: "N",
  },
  {
    appId: 4080,
    appName: "DALCOMP",
    state: "Operate",
    lob: "CIB",
    JPMC_SOX: "N",
    JPMC_CCAP: "N",
    SSAE_SOCI: "N",
    PCI: "N",
    PHI: "Y",
    GLBA: "N",
    MNPI: "N",
    HVBE: "N",
  },
  {
    appId: 5060,
    appName: "Easy Tributos",
    state: "Operate",
    lob: "CIB",
    JPMC_SOX: "N",
    JPMC_CCAP: "N",
    SSAE_SOCI: "N",
    PCI: "N",
    PHI: "N",
    GLBA: "Y",
    MNPI: "Y",
    HVBE: "N",
  },
  {
    appId: 5440,
    appName: "EQFA(Equity Finance Accounting)",
    state: "Operate",
    lob: "CIB",
    JPMC_SOX: "Y",
    JPMC_CCAP: "Y",
    SSAE_SOCI: "Y",
    PCI: "Y",
    PHI: "N",
    GLBA: "N",
    MNPI: "N",
    HVBE: "N",
  },
  {
    appId: 5680,
    appName: "Client Billing",
    state: "Operate",
    lob: "CIB",
    JPMC_SOX: "Y",
    JPMC_CCAP: "Y",
    SSAE_SOCI: "Y",
    PCI: "N",
    PHI: "N",
    GLBA: "N",
    MNPI: "Y",
    HVBE: "N",
  },
  {
    appId: 5970,
    appName: "Content Manager(IPB)",
    state: "Operate",
    lob: "AWM",
    JPMC_SOX: "N",
    JPMC_CCAP: "N",
    SSAE_SOCI: "Y",
    PCI: "N",
    PHI: "N",
    GLBA: "Y",
    MNPI: "N",
    HVBE: "N",
  },
  {
    appId: 6750,
    appName: "fxXpress",
    state: "Operate",
    lob: "CIB",
    JPMC_SOX: "N",
    JPMC_CCAP: "N",
    SSAE_SOCI: "Y",
    PCI: "Y",
    PHI: "N",
    GLBA: "N",
    MNPI: "N",
    HVBE: "N",
  },
  {
    appId: 6830,
    appName: "GMI",
    state: "Operate",
    lob: "CIB",
    JPMC_SOX: "Y",
    JPMC_CCAP: "Y",
    SSAE_SOCI: "Y",
    PCI: "N",
    PHI: "N",
    GLBA: "Y",
    MNPI: "N",
    HVBE: "N",
  },
  {
    appId: 7590,
    appName: "US Workstations Headsheets",
    state: "Operate",
    lob: "AWM",
    JPMC_SOX: "N",
    JPMC_CCAP: "N",
    SSAE_SOCI: "Y",
    PCI: "N",
    PHI: "N",
    GLBA: "N",
    MNPI: "N",
    HVBE: "N",
  },
  {
    appId: 7722,
    appName: "High Yield Index",
    state: "Operate",
    lob: "CIB",
    JPMC_SOX: "N",
    JPMC_CCAP: "N",
    SSAE_SOCI: "Y",
    PCI: "Y",
    PHI: "N",
    GLBA: "N",
    MNPI: "N",
    HVBE: "N",
  },
  {
    appId: 8170,
    appName: "JPO International",
    state: "Operate",
    lob: "AWM",
    JPMC_SOX: "N",
    JPMC_CCAP: "N",
    SSAE_SOCI: "Y",
    PCI: "N",
    PHI: "Y",
    GLBA: "Y",
    MNPI: "N",
    HVBE: "N",
  },
  {
    appId: 8190,
    appName: "IRESS IOS",
    state: "Operate",
    lob: "CIB",
    JPMC_SOX: "N",
    JPMC_CCAP: "N",
    SSAE_SOCI: "Y",
    PCI: "N",
    PHI: "N",
    GLBA: "Y",
    MNPI: "N",
    HVBE: "N",
  },
  {
    appId: 8230,
    appName: "Fixed Income International Settlement",
    state: "Operate",
    lob: "CIB",
    JPMC_SOX: "Y",
    JPMC_CCAP: "Y",
    SSAE_SOCI: "Y",
    PCI: "N",
    PHI: "N",
    GLBA: "N",
    MNPI: "N",
    HVBE: "N",
  },
  {
    appId: 8470,
    appName: "Interest Rate Front End",
    state: "Retired",
    lob: "CIB",
    JPMC_SOX: "N",
    JPMC_CCAP: "N",
    SSAE_SOCI: "N",
    PCI: "N",
    PHI: "N",
    GLBA: "N",
    MNPI: "N",
    HVBE: "N",
  },
  {
    appId: 8630,
    appName: "JAFFA",
    state: "Operate",
    lob: "AWM",
    JPMC_SOX: "N",
    JPMC_CCAP: "N",
    SSAE_SOCI: "Y",
    PCI: "N",
    PHI: "N",
    GLBA: "N",
    MNPI: "Y",
    HVBE: "N",
  },
];

export default data;
